version: '3.8'

services:
  # PHP 服務
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # 這裡指定使用開發階段
    container_name: uwow-app
    volumes:
      - .:/var/www/html:delegated
    networks:
      - uwow-network
    command: sh -c "php-fpm"
    depends_on:
      db:
        condition: service_healthy
  # Nginx 服務
  web:
    image: nginx:alpine
    container_name: uwow-web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - uwow-network

  # MySQL 服務
  db:
    image: mysql:8.0
    container_name: uwow-db
    ports:
      - "3306:3306"
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - uwow-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  # redis 服務
  redis:
    image: redis:7-alpine
    container_name: uwow-redis
    restart: always
    networks:
      - uwow-network
    ports:
      - "6379:6379"

  # worker 服務
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # 這裡指定使用開發階段
    container_name: uwow-worker
    command: php artisan queue:work
    user: "1000:1000"
    volumes:
      - .:/var/www/html
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - uwow-network
networks:
  uwow-network:
    driver: bridge

volumes:
  db-data:
